# Generated by Django 2.0.6 on 2018-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igaccount', models.CharField(help_text='account for direct', max_length=30)),
                ('igpassword', models.CharField(help_text='password of account', max_length=30)),
            ],
            options={
                'verbose_name': 'account for direct',
                'verbose_name_plural': 'account for direct',
            },
        ),
        migrations.CreateModel(
            name='IGmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igmodel', models.CharField(help_text='model account', max_length=30)),
                ('msg_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name='date of dm')),
            ],
            options={
                'verbose_name': 'model account',
                'verbose_name_plural': 'model account',
            },
        ),
    ]
