# Generated by Django 2.0.6 on 2018-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igmain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igmodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='igaccount',
            name='igpassword',
            field=models.CharField(help_text='account for direct', max_length=30),
        ),
    ]
