# Generated by Django 2.0.6 on 2018-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igmain', '0002_auto_20180908_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGpublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igpublic', models.CharField(help_text='public account', max_length=30)),
            ],
            options={
                'verbose_name': 'public',
                'verbose_name_plural': 'public',
            },
        ),
        migrations.AlterField(
            model_name='igaccount',
            name='igaccount',
            field=models.CharField(help_text='account', max_length=30),
        ),
        migrations.AlterField(
            model_name='igaccount',
            name='igpassword',
            field=models.CharField(help_text='password', max_length=30),
        ),
    ]
